# Generated by Django 3.1.7 on 2021-03-10 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='link',
        ),
        migrations.AddField(
            model_name='publication',
            name='abstract',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='publication',
            name='conference',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='year',
            field=models.PositiveSmallIntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=1000),
        )
    ]
