# Generated by Django 3.1.7 on 2021-03-11 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20210310_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationAssociatedAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correspondingAuthor', models.BooleanField(default=False)),
                ('authorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.publicationauthor')),
                ('publicationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.publication')),
            ],
        )
    ]
