# Generated by Django 3.1.7 on 2021-03-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20210311_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationassociatedauthor',
            old_name='authorID',
            new_name='authorId',
        ),
    ]
