# Generated by Django 3.1.7 on 2021-03-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20210311_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='publicationassociatedauthor',
            name='authorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorId', to='portal.publicationauthor'),
        ),
        migrations.AlterField(
            model_name='publicationassociatedauthor',
            name='publicationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicationId', to='portal.publication'),
        ),
    ]
