# Generated by Django 3.1.7 on 2021-03-11 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20210311_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationassociatedauthor',
            name='authorId',
        ),
        migrations.RemoveField(
            model_name='publicationassociatedauthor',
            name='publicationId',
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(through='portal.PublicationAssociatedAuthor', to='portal.PublicationAuthor'),
        ),
        migrations.AddField(
            model_name='publicationassociatedauthor',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.publicationauthor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicationassociatedauthor',
            name='publication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.publication'),
            preserve_default=False,
        ),
    ]
